name: branchwater-dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.8.14,<5
    - sourmash_plugin_branchwater==0.9.13
    - pip
    - pandas
    - pytaxonkit
    - requests
    - upsetplot